---
- name: Customize our Nginx Web Page
  hosts: webservers
  gather_facts: false

  tasks:
    - name: Install Python first
      raw: apt-get update && apt-get install -y python3

    - name: Create a custom index.html
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <h1>Wow! Ansible actually works!</h1>
          <p>Terraform built the server, and Ansible customized it.</p>